#!/bin/bash
# AngazaCare Deployment Script
# This script helps deploy AngazaCare to various platforms

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║          AngazaCare Deployment Setup                     ║"
echo "╚═══════════════════════════════════════════════════════════╝"

echo ""
echo "Choose your deployment platform:"
echo "1) Render.com (Recommended - Free tier available)"
echo "2) Heroku"
echo "3) AWS"
echo "4) Local Docker (Development)"
echo ""

# For now, show Render instructions
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║   Render.com Deployment (Recommended)                     ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "STEP 1: Prepare Your Code"
echo "────────────────────────"
echo "  $ git init"
echo "  $ git add ."
echo "  $ git commit -m 'Initial commit - AngazaCare'"
echo "  $ git remote add origin <your-github-repo-url>"
echo "  $ git push -u origin main"
echo ""
echo "STEP 2: Deploy on Render"
echo "────────────────────────"
echo "  1. Visit: https://dashboard.render.com"
echo "  2. Click: 'New +' → 'Web Service'"
echo "  3. Connect your GitHub repository"
echo "  4. Configure:"
echo "     - Name: angazacare"
echo "     - Environment: Docker"
echo "     - Branch: main"
echo "     - Dockerfile path: ./Dockerfile"
echo ""
echo "STEP 3: Add Environment Variables"
echo "─────────────────────────────────"
echo "  In Render Dashboard → Environment:"
echo "  - GEMINI_API_KEY: <your-api-key>"
echo "  - USE_FALLBACK_ONLY: false"
echo ""
echo "STEP 4: Deploy"
echo "──────────────"
echo "  Click 'Create Web Service' and wait 2-5 minutes"
echo ""
echo "STEP 5: Access Your App"
echo "───────────────────────"
echo "  Your URL will be: https://angazacare-xxxx.onrender.com"
echo "  Login with:"
echo "    Email: admin@angazacare.com"
echo "    Password: admin123"
echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║        Local Docker (Development)                         ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "  $ docker-compose up --build"
echo "  Access at: http://localhost:5000"
echo ""
